### ISSUE TITLE
ValueError: Dimensions must be equal when trained my dataset

### ISSUE THREAD

**Issue by sunyongke** [kwotsin/TensorFlow-ENet#43]
I runed the demo code, it perfect and no errors.

but shows errors when using my own dataset. 

the image size is 400x400, the annotated image has same size,  the background is 0, the target eara is 1.

 

(py36) [syk@gtx1070 TensorFlow-ENet]$ python train_enet.py --weighting="ENET" --num_epochs=300 --logdir="./log/train_original_E
Net_knot" --num_classes=2 --image_width=400 --image_height=400                                                                 
========= ENet Class Weights =========                                                                                         
 [1.8298322321992648, 3.6742181094502975, 50.4983497918439, 50.4983497918439, 50.4983497918439, 50.4983497918439, 50.4983497918
439, 50.4983497918439, 50.4983497918439, 50.4983497918439, 50.4983497918439, 0.0]                                              
WARNING:tensorflow:From train_enet.py:142: slice_input_producer (from tensorflow.python.training.input) is deprecated and will 
be removed in a future version.                                                                                                
Instructions for updating:                                                                                                     
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(tuple(tensor_list)).shuffl
e(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.             
WARNING:tensorflow:From /home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/input.py:372: ran
ge_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.               
Instructions for updating:                                                                                                     
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.range(limit).shuffle(limit).repeat(num_epochs
)`. If `shuffle=False`, omit the `.shuffle(...)`.                                                                              
WARNING:tensorflow:From /home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/input.py:318: inp
ut_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.                     
Instructions for updating:                                                                                                     
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.s
hape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.                   
WARNING:tensorflow:From /home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/input.py:188: lim
it_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.                       
Instructions for updating:                                                                                                     
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.    
WARNING:tensorflow:From /home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/input.py:197: Que
ueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.   
Instructions for updating:                                                                                                     
To construct input pipelines, use the `tf.data` module.                                                                        
WARNING:tensorflow:From /home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/input.py:197: add
_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.       
Instructions for updating:                                                                                                     
To construct input pipelines, use the `tf.data` module.                                                                        
WARNING:tensorflow:From train_enet.py:152: batch (from tensorflow.python.training.input) is deprecated and will be removed in a
 future version.                                                                                                               
Instructions for updating:                       
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if
 `dynamic_pad=True`).          
inputs_shape [None, 400, 400, 3]
Traceback (most recent call last):
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c
_op                            
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 2 and 12 for 'mul' (op: 'Mul') 
with input shapes: [10,400,400,2], [12].                       

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_enet.py", line 338, in <module>
    run()
  File "train_enet.py", line 170, in run
    loss = weighted_cross_entropy(logits=logits, onehot_labels=annotations_ohe, class_weights=class_weights)
  File "train_enet.py", line 128, in weighted_cross_entropy
    weights = onehot_labels * class_weights
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 878, in binary_op_w
rapper                         
    return func(x, y, name=name)
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1131, in _mul_dispa
tch                            
    return gen_math_ops.mul(x, y, name=name)
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5042, in mul   
    "Mul", x=x, y=y, name=name) 
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in
 _apply_op_helper              
    op_def=op_def)
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_fun
c                              
    return func(*args, **kwargs)
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__ 
    control_input_ops)
  File "/home/syk/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c
_op                            
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 2 and 12 for 'mul' (op: 'Mul') with input shapes: [10,400,400,2], [12].

**Comment by lapetite123** [comment]
hello, I noticed the code only running on gpu 0, although I set cuda_visiable_devices=1. can you please tell me how to set gpu 2 to train the code. thanks!
